### ISSUE TITLE
Can this be installed on User files?

### ISSUE THREAD

**Issue by Gfurst** [fauu/Kamite#2]
For example, `~/.local/urs/bin`

I'd rather avoid installing root stuff without system packages, as not avoid having loose files.

edit:giving a proper look at the files, doesn't seem like much of the files are installed, besides the binary itself, icons and shortcut. Are the other files in the release provided as a sort of portable version? If that's the case I could just try manually installing to local.

**Comment by fauu** [comment]
Installation is optional. You can extract the archive anywhere and immediately run the program by launching the `bin/kamite` script from anywhere.
