### ISSUE TITLE
Character Counter

### ISSUE THREAD

**Issue by randomuser4412** [fauu/Kamite#6]
Hi, I noticed that the character counter includes things such as 「」… 。, and everything else which makes it pretty inaccurate, could they be filtered out of character counter like the other texthooking pages do it?

**Comment by fauu** [comment]
Thanks for the suggestion. Starting from next release, the counter will have some filtering.

**Comment by fauu** [comment]
In [v0.6](https://github.com/fauu/Kamite/releases/tag/v0.6) only characters in Unicode categories Letter, Number, and Symbol are counted. Might add an option to customize this later on.
