### ISSUE TITLE
can't run version 0.6

### ISSUE THREAD

**Issue by randomuser4412** [fauu/Kamite#7]
Hello, after downloading 0.6 version and extracting it when I try to run kamite nothing happens and an hs_err file is being generated. Version 0.5 didn't have any issues. Any idea what I could do?

[hs_err_pid11864.log](https://github.com/fauu/Kamite/files/9549315/hs_err_pid11864.log)

**Comment by fauu** [comment]
Does it work if you remove `runtime/` and `Kamite.exe` from 0.6 and replace them with the old versions from 0.5? If it does, then this can be used as a workaround until I figure out the problem.

**Comment by fauu** [comment]
Most probably fixed in [v0.7](https://github.com/fauu/Kamite/releases/tag/v0.7), but please let me know if it still happens.
